image: node:latest

stages:
  - build
  - test_e2e

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm install yarn
   - npm install @angular/cli
   - yarn install
   - yarn build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

test_e2e:
  stage: test_e2e
  script:
   - apt install chromium-browser -y
   - yarn e2e
  artifacts:
    paths:
      - e2e/output/*
    expire_in: 1 week
