image: node:latest

stages:
  - build
  - test_e2e

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm install yarn
   - npm install @angular/cli
   - yarn install
   - yarn build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

test_e2e:
  stage: test_e2e
  before_script:
   - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
  script:
   - yarn e2e
  artifacts:
    paths:
      - e2e/output/*
    expire_in: 1 week
